version: '3.8'

services:
  comfyui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: comfyui
    restart: unless-stopped
    ports:
      - "8188:8188"
    volumes:
      - ./models:/app/models
      - ./custom_nodes:/app/custom_nodes
      - ./input:/app/input
      - ./output:/app/output
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu] 